# ✅ Fixed Configuration Based on Your Current Setup
recipe: default.v1

# Keep your existing assistant ID
assistant_id: 20250603-171246-violent-ion

# Configuration for Rasa NLU
language: en

# ✅ ACTIVATED: Proper pipeline configuration (no more null!)
pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 150  # ✅ Increased from default 100
    constrain_similarities: true
    model_confidence: softmax  # ✅ Fixed for newer Rasa versions
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 150  # ✅ Increased from default 100
    constrain_similarities: true
  # ✅ CRITICAL: Fixed fallback threshold for better recognition
  - name: FallbackClassifier
    threshold: 0.6  # ✅ Lowered from 0.3 for better fallback detection
    ambiguity_threshold: 0.1

# ✅ ACTIVATED: Proper policies configuration (no more null!)
policies:
  - name: MemoizationPolicy
    max_history: 5
  - name: RulePolicy
    # ✅ CRITICAL: Proper fallback configuration
    core_fallback_threshold: 0.3
    core_fallback_action_name: "utter_default"
    enable_fallback_prediction: true
  - name: UnexpecTEDIntentPolicy
    max_history: 5
    epochs: 150  # ✅ Increased from default 100
  - name: TEDPolicy
    max_history: 5
    epochs: 150  # ✅ Increased from default 100
    constrain_similarities: tru